### ISSUE TITLE
using

### ISSUE THREAD

**Issue by balbulator** [definitio/ha-rhvoice#1]
Give an example of use. I have a Raspberry Pi4, HA. For example, event driven automation - playing "text" or script - playing a file ... / ... .mp3

**Comment by definitio** [comment]
There are 2 ways to call any TTS platform:
1. Use HA service `say` ([documentation](https://www.home-assistant.io/integrations/tts/#service-say)):
```yaml
service: tts.rhvoice
entity_id: media_player.<entity id>
data:
  message: Hello
```
2. Use Web UI: click on media player end enter text
![Screenshot_20200817_190743](https://user-images.githubusercontent.com/37266727/90411712-38867c80-e0bd-11ea-8426-6804a21a122e.png)

Automation example:
```yaml
- alias: water_leak_notification
  trigger:
    - platform: state
      entity_id:  binary_sensor.bathroom_water_leak
      from: "off"
      to: "on"
  action:
    - service: tts.rhvoice
      data:
        message: Water leak detected
```
