### ISSUE TITLE
Improve Documentation regarding configuration

### ISSUE THREAD

**Issue by frederickjh** [definitio/ha-rhvoice#3]
Hi!

I have now gotten **ha-rhvoice** configured on my Home Assistant setup. I am using a domain name with a SSL certificate. Currently from the documentation it is not clearly evident how to correctly set this up. I have the following in my Home Assistant `configuration.yml` file:
```yaml
# Text to speech
tts:
  - platform: rhvoice
    host: example.com
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: rhvoice_say
    # Optional
    port: 8880
    # Optional, wav|mp3|opus|flac
    format: 'mp3'
    # Optional, 0..100
    pitch: 50
    # Optional, 0..100
    rate: 50
    # Optional, default is 'anna' (russian)
    voice: 'alan'
    # Optional, 0..100
    volume: 100
```

Previously I had **host:** set to the LAN IP address of the computer running Home Assistant via docker and the **aculeasis/rhvoice-rest** container. I also had **port:** set to **8080**. However because I am using port 8080 for something else (and have it forwarded to a different computer on the LAN) I have forwarded port **8880** on my router to the Home Assistant computer's port **8080**.

So if I am understanding this correctly **Host:**  and **Port:** need to be set to the hostname and port that the **rhvoice-rest** container can be reached at.

If that is true then I suggest changing the configuration example in the documentation to the following:

```yaml
tts:
  - platform: rhvoice
    # This is the hostname or domain name that the rhvoice-rest container can be reached at.
    host: <server hostname or IP address>
    # This is the port that the rhvoice-rest container can be reached at. 
    # For external access you need to forward this port on your router to the computer running the rhvoice-rest container.
    port: 8080
    # Optional, wav|mp3|opus|flac
    format: 'mp3'
   # Optional, 0..100
    pitch: 50
   # Optional, 0..100
    rate: 50
   # Optional, default is 'anna' (russian)
    voice: 'anna'
    # Optional, 0..100
    volume: 50
```
In addition to the comments I have moved the comments to the line above the YAML, as Home Assistant does not like comments after the YAML.

I am willing to submit a pull request. If you would like this structured differently, say with shorter comments in the configuration and a separate section explaining the configuration file options I can do this too.

Frederick
